pipeline {
    agent any

    environment {
        DOCKER_USER = "cherrypopuwu"
    }

    stages {

        stage('Clonar repo') {
            steps {
                git 'https://github.com/CHERRYPOPUwU/minihotel.git'
            }
        }

        stage('Build imágenes') {
            steps {
                sh '''
                docker build -t $DOCKER_USER/api-gateway:latest -f docker/api-gateway.Dockerfile .
                docker build -t $DOCKER_USER/frontend:latest -f docker/frontend.Dockerfile .
                docker build -t $DOCKER_USER/user-service:latest -f docker/user-service.Dockerfile .
                docker build -t $DOCKER_USER/room-service:latest -f docker/room-service.Dockerfile .
                docker build -t $DOCKER_USER/booking-service:latest -f docker/booking-service.Dockerfile .
                '''
            }
        }

        stage('Login DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }

        stage('Push imágenes') {
            steps {
                sh '''
                docker push $DOCKER_USER/api-gateway:latest
                docker push $DOCKER_USER/frontend:latest
                docker push $DOCKER_USER/user-service:latest
                docker push $DOCKER_USER/room-service:latest
                docker push $DOCKER_USER/booking-service:latest
                '''
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh '''
                kubectl rollout restart deployment api-gateway
                kubectl rollout restart deployment frontend
                kubectl rollout restart deployment user-service
                kubectl rollout restart deployment room-service
                kubectl rollout restart deployment booking-service
                '''
            }
        }
    }
}